-- MFS Balance Sheet measure definitions (024). Fifth and final MFS sibling
-- workbook (item 7.1). Semantics, label-drift evidence, and the deliberately
-- excluded early years (FY2005-06/06-07/07-08) are documented in
-- config/measure-semantics/mfs.yaml and ops/reports/mfs-balance-sheet-*.md.
--
-- additive_across_time = 0 for all: a stock has no YTD accumulation to sum.
-- additive_across_nodes = 1 for line items that genuinely sum to one of the 4
-- published subtotals (Total financial assets, Total non-financial assets,
-- Total interest bearing liabilities, Total provisions and payables) - a real,
-- source-stated relationship, matching Note 3's total_expenses pattern.
-- root_total_allowed = 0 for the 4 subtotals themselves and the 2 net-position
-- measures (already-derived, never themselves an addend).

INSERT OR IGNORE INTO measure_definitions
    (measure_type, label, description, additive_across_time, additive_across_nodes,
     default_accounting_basis, compatibility_group, view_family, default_unit, root_total_allowed)
VALUES
    ('mfs_balance_sheet_advances_paid', 'MFS Balance Sheet: Advances paid',
     'MFS Balance Sheet: Advances paid, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_advances_paid', NULL, 'AUD', 1),
    ('mfs_balance_sheet_investments_loans_placements', 'MFS Balance Sheet: Investments, loans and placements',
     'MFS Balance Sheet: Investments, loans and placements, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_investments_loans_placements', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_receivables', 'MFS Balance Sheet: Other receivables',
     'MFS Balance Sheet: Other receivables, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_receivables', NULL, 'AUD', 1),
    ('mfs_balance_sheet_investments_other_public_sector_entities', 'MFS Balance Sheet: Investments in other public sector entities',
     'MFS Balance Sheet: Investments in other public sector entities, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_investments_other_public_sector_entities', NULL, 'AUD', 1),
    ('mfs_balance_sheet_equity_accounted_investments', 'MFS Balance Sheet: Equity accounted investments',
     'MFS Balance Sheet: Equity accounted investments, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_equity_accounted_investments', NULL, 'AUD', 1),
    ('mfs_balance_sheet_investments_shares', 'MFS Balance Sheet: Investments - shares',
     'MFS Balance Sheet: Investments - shares, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_investments_shares', NULL, 'AUD', 1),
    ('mfs_balance_sheet_biological_assets', 'MFS Balance Sheet: Biological assets',
     'MFS Balance Sheet: Biological assets, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_biological_assets', NULL, 'AUD', 1),
    ('mfs_balance_sheet_assets_held_for_sale', 'MFS Balance Sheet: Assets held for sale',
     'MFS Balance Sheet: Assets held for sale, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_assets_held_for_sale', NULL, 'AUD', 1),
    ('mfs_balance_sheet_land', 'MFS Balance Sheet: Land',
     'MFS Balance Sheet: Land, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_land', NULL, 'AUD', 1),
    ('mfs_balance_sheet_buildings', 'MFS Balance Sheet: Buildings',
     'MFS Balance Sheet: Buildings, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_buildings', NULL, 'AUD', 1),
    ('mfs_balance_sheet_plant_equipment_infrastructure', 'MFS Balance Sheet: Plant, equipment and infrastructure',
     'MFS Balance Sheet: Plant, equipment and infrastructure, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_plant_equipment_infrastructure', NULL, 'AUD', 1),
    ('mfs_balance_sheet_inventories', 'MFS Balance Sheet: Inventories',
     'MFS Balance Sheet: Inventories, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_inventories', NULL, 'AUD', 1),
    ('mfs_balance_sheet_intangibles', 'MFS Balance Sheet: Intangibles',
     'MFS Balance Sheet: Intangibles, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_intangibles', NULL, 'AUD', 1),
    ('mfs_balance_sheet_heritage_cultural_assets', 'MFS Balance Sheet: Heritage and cultural assets',
     'MFS Balance Sheet: Heritage and cultural assets, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_heritage_cultural_assets', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_non_financial_assets', 'MFS Balance Sheet: Other non-financial assets',
     'MFS Balance Sheet: Other non-financial assets, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_non_financial_assets', NULL, 'AUD', 1),
    ('mfs_balance_sheet_deposits_held', 'MFS Balance Sheet: Deposits held',
     'MFS Balance Sheet: Deposits held, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_deposits_held', NULL, 'AUD', 1),
    ('mfs_balance_sheet_government_securities', 'MFS Balance Sheet: Government securities',
     'MFS Balance Sheet: Government securities, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_government_securities', NULL, 'AUD', 1),
    ('mfs_balance_sheet_loans', 'MFS Balance Sheet: Loans',
     'MFS Balance Sheet: Loans, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_loans', NULL, 'AUD', 1),
    ('mfs_balance_sheet_superannuation_liability', 'MFS Balance Sheet: Superannuation liability',
     'MFS Balance Sheet: Superannuation liability, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_superannuation_liability', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_employee_liabilities', 'MFS Balance Sheet: Other employee liabilities',
     'MFS Balance Sheet: Other employee liabilities, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_employee_liabilities', NULL, 'AUD', 1),
    ('mfs_balance_sheet_investment_property', 'MFS Balance Sheet: Investment property/properties',
     'MFS Balance Sheet: Investment property/properties, as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_investment_property', NULL, 'AUD', 1),
    ('mfs_balance_sheet_suppliers_payable', 'MFS Balance Sheet: Suppliers payable(s)',
     'MFS Balance Sheet: Suppliers payable(s), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_suppliers_payable', NULL, 'AUD', 1),
    ('mfs_balance_sheet_personal_benefits_payable', 'MFS Balance Sheet: Personal benefits payable(s)',
     'MFS Balance Sheet: Personal benefits payable(s), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_personal_benefits_payable', NULL, 'AUD', 1),
    ('mfs_balance_sheet_subsidies_payable', 'MFS Balance Sheet: Subsidies payable(s)',
     'MFS Balance Sheet: Subsidies payable(s), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_subsidies_payable', NULL, 'AUD', 1),
    ('mfs_balance_sheet_grants_payable', 'MFS Balance Sheet: Grants payable(s)',
     'MFS Balance Sheet: Grants payable(s), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_grants_payable', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_borrowing', 'MFS Balance Sheet: Other borrowing (FY2008-09..FY2018-19 only)',
     'MFS Balance Sheet: Other borrowing (FY2008-09..FY2018-19 only), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_borrowing', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_provisions_and_payables', 'MFS Balance Sheet: Other provisions and payables (FY2008-09..FY2016-17 only)',
     'MFS Balance Sheet: Other provisions and payables (FY2008-09..FY2016-17 only), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_provisions_and_payables', NULL, 'AUD', 1),
    ('mfs_balance_sheet_other_payables', 'MFS Balance Sheet: Other payables (FY2017-18 onward)',
     'MFS Balance Sheet: Other payables (FY2017-18 onward), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_other_payables', NULL, 'AUD', 1),
    ('mfs_balance_sheet_provisions', 'MFS Balance Sheet: Provisions (FY2017-18 onward)',
     'MFS Balance Sheet: Provisions (FY2017-18 onward), as at the last calendar day of the reporting month.',
     0, 1, 'accrual', 'mfs_balance_sheet_provisions', NULL, 'AUD', 1),
    ('mfs_balance_sheet_total_financial_assets', 'MFS Balance Sheet: Total financial assets',
     'MFS Balance Sheet: Total financial assets, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_total_financial_assets', NULL, 'AUD', 0),
    ('mfs_balance_sheet_total_non_financial_assets', 'MFS Balance Sheet: Total non-financial assets',
     'MFS Balance Sheet: Total non-financial assets, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_total_non_financial_assets', NULL, 'AUD', 0),
    ('mfs_balance_sheet_total_interest_bearing_liabilities', 'MFS Balance Sheet: Total interest bearing liabilities',
     'MFS Balance Sheet: Total interest bearing liabilities, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_total_interest_bearing_liabilities', NULL, 'AUD', 0),
    ('mfs_balance_sheet_total_provisions_and_payables', 'MFS Balance Sheet: Total provisions and payables',
     'MFS Balance Sheet: Total provisions and payables, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_total_provisions_and_payables', NULL, 'AUD', 0),
    ('mfs_balance_sheet_net_financial_worth', 'MFS Balance Sheet: Net financial worth',
     'MFS Balance Sheet: Net financial worth, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_net_financial_worth', NULL, 'AUD', 0),
    ('mfs_balance_sheet_net_financial_liabilities', 'MFS Balance Sheet: Net financial liabilities',
     'MFS Balance Sheet: Net financial liabilities, as at the last calendar day of the reporting month. A derived figure, directly cited from the source''s own stated row - never computed here.',
     0, 0, 'accrual', 'mfs_balance_sheet_net_financial_liabilities', NULL, 'AUD', 0);
